language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g tsd
  - bower --version
  - tsd --version
  - bower install
  - tsd reinstall
script: npm test