language: node_js
node_js:
  - 0.10
before_script:
  - node_modules/.bin/grunt --version
  - node_modules/.bin/bower --version
  - node_modules/.bin/tsd --version
  - node_modules/.bin/bower install
  - node_modules/.bin/tsd reinstall
script: npm test